apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: my-daemon
  name: my-daemon
spec:
  selector:
    matchLabels:
      app: my-daemon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-daemon
    spec:
      containers:
      - image: bitnami/node-exporter:latest
        name: node-exporter
        resources: {}
status: {}
