groups:
- name: example
  labels:
    team: myteam
  rules:
  - alert: server is down
    expr: up{job="prometheus",instance="node_exporter:9100"} == 0
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: page
    annotations:
      summary: Node Exporter is down on instance {{ $labels.instance }}
     # description: "Node Exporter has been down for more than 1 minute.\n