apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: myapp
  name: np-svc
  namespace: apps
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: myapp
  type: NodePort
status:
  loadBalancer: {}
